# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - .:/var/www:cached
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # указываем путь к образу PHP и говорим что его надо собрать
    build:
      context: ./docker/config
      dockerfile: php
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектами
    volumes:
      - .:/var/www:cached
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /etc/mysql:/etc/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
      - ./data:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  node:
    image: node:14
    working_dir: /var/www
    command: [ "bash", "-c", "npm install && npm run watch" ]
    volumes:
      - ./:/var/www

  adminer:
    image: adminer
    ports:
      - "8080:8080"

